### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by armyhcz** [thjiang/easyV2#1]
ERR:Error: timeout of 5000ms exceeded
经常错误

**Comment by thjiang** [comment]
> ERR:Error: timeout of 5000ms exceeded
> 经常错误

直接 curl 一下这样的接口地址试试是不是网络问题导致接口超时了？
https://www.v2ex.com/api/topics/show.json?id=613097

**Comment by armyhcz** [comment]
现在好了,我估计是v2ex网络波动
